### ISSUE TITLE
Account restore 

### ISSUE THREAD

**Issue by Thimzy1308** [unisat-wallet/dev-support#1]
please am trying to restore my unisat wallet but the continue button is not clicking
![Screenshot_20240210-165005](https://github.com/unisat-wallet/unisat-dev-support/assets/159551869/d72b9569-80c9-4c51-9275-6cd1cde478b2)

**Comment by Thimzy1308** [comment]
Please any solution

**Comment by huanniangstudio** [comment]
This is usually because of the use of illegal mnemonic words, and the presence of spaces before and after will also cause it to be invalid.
