### ISSUE TITLE
Gas fees related- feeRate

### ISSUE THREAD

**Issue by yusufshaikh0110** [unisat-wallet/dev-support#16]
i have taken code from docs 1month ago its working but now it is not showing gas fees i don't know 
here is my code 
const txId = await window.unisat.sendBitcoin(
          SATOSHI_VAULT_ADDRESS,
          calcultedAmount,
          {
            feeRate: fee,
          }
        );
        
when i click on register then unisat wallet is showing and it is also showing an warning about a fee rate is high or bla bla 
but now it is showing nothing the code is same i have change nothing it is not showing gas fee

**Comment by abangZ** [comment]
![image](https://github.com/unisat-wallet/dev-support/assets/12698717/47a84727-a724-4cad-904a-9c9bfaeb5d7f)

We have modified the fee rate reminder.
