### ISSUE TITLE
How to get all Rune UTXOs for an address?

### ISSUE THREAD

**Issue by lifofifoX** [unisat-wallet/dev-support#19]
Is there a method similar to `unisat.getInscriptions(cursor,size)` - but for getting utxos with any Rune balances?

**Comment by abangZ** [comment]
https://docs.unisat.io/dev/unisat-developer-service/runes/get-address-runes-utxo

**Comment by lifofifoX** [comment]
@abangZ Was hoping to avoid an API call.
