### ISSUE TITLE
Get the txId without submitting a tx

### ISSUE THREAD

**Issue by elRaulito** [unisat-wallet/dev-support#2]
I would like to request 2 features:

1. Signing a rawTx I created externally
2. Being able to get the txId without submitting it (this allows to create transactions based on this one)

**Comment by huanniangstudio** [comment]
https://github.com/unisat-wallet/dev-support/blob/master/wallet-sdk-examples/example/send-btc.ts#L62
You can refer to this.

```
 const tx = psbt.extractTransaction(true);
 const txid = tx.getId(); 
```
