### ISSUE TITLE
Hice una inscripción y nunca me llegaron los tokens 

### ISSUE THREAD

**Issue by Orellana129** [unisat-wallet/dev-support#21]
Hola el 20 de abril hice una inscripción de SATOSHI NAKAMOTO más sin embargo nunca me llegaron los runes que mintie y lo hice en su marketplace la transacción me dice confirmada pero jamás me llegaron los tokens me podrían ayudar?

**Comment by abangZ** [comment]
SATOSHI NAKAMOTO has a limit on the total amount of casting. On April 20th, the network was too congested, and your order was not confirmed before the completion of the SATOSHI NAKAMOTO mint.
