### ISSUE TITLE
API for Get statistical data, price, market capitalization, etc. for BRC20. Not working

### ISSUE THREAD

**Issue by martianatwork** [unisat-wallet/dev-support#22]
Here is the API which I'm using:
https://open-api.unisat.io/v3/market/brc20/auction/brc20_types_specified

Body
```
{
  "timeType": "day1",
  "tick": "ordi"
}
```

Expected response:
```
{
  "code": 0,
  "msg": "text",
  "data": {
    "tick": "text",
    "curPrice": 0,
    "changePrice": 0,
    "btcVolume": 0,
    "amountVolume": 0
  }
}

```

Actual Response:
```
{
  "code": 0,
  "msg": "ok",
  "data": false
}
```

i have sent the auth headers as well

am i missing something?

**Comment by abangZ** [comment]
Thank you for your feedback. We have fixed the issue. please try again.
