### ISSUE TITLE
Got message "offChain" is not allowed" 

### ISSUE THREAD

**Issue by cloud6605** [unisat-wallet/dev-support#31]
![image](https://github.com/unisat-wallet/dev-support/assets/132422140/ee796e8e-ed2b-4fcd-b582-f840acc9851a)

When we use offChain as either true or false we are receiving error as 

 {
code: 'FST_ERR_VALIDATION',
msg: '"offChain" is not allowed',
data: null }

When we remove and use we are getting as above shared what eaxctly we error mean

**Comment by abangZ** [comment]
This parameter is currently only supported on the mainnet. We will update the testnet service as soon as possible.

**Comment by abangZ** [comment]
We have already supported this parameter on the testnet. Please try again.
