### ISSUE TITLE
Error : {   "code": -2003,   "msg": "quota unavailable",   "data": null }

### ISSUE THREAD

**Issue by Nate-Expert** [unisat-wallet/dev-support#37]
I am trying Swagger link https://open-api-testnet.unisat.io/swagger.html to test few api for incribe a brc-20 token with API key i got from developer.unisat.io. I am getting Error : {   "code": -2003,   "msg": "quota unavailable",   "data": null } error in response. Please let me know is there anything i am missing. In production same API key is working but not on testnet.

**Comment by huanniangstudio** [comment]
Please provide the first 6 digits of your API-KEY, we will check it.

**Comment by Nate-Expert** [comment]
> Please provide the first 6 digits of your API-KEY, we will check it.
here it is:

3141d9

**Comment by Nate-Expert** [comment]
This is working now. Thanks

**Comment by Avecci-Claussen** [comment]
hi , i got the same issue , tried regen the key still quota unavailable but on dashboard i do have quota : 

last 6 of my key : f6acae

thanks for understanding.

example of the command im using to grab my inscriptions ids : 

curl -H "Authorization: Bearer api" https://open-api.unisat.io/v1/indexer/address/bc1qcagueggs2snz8uvh92qfffglu3hzqxmwvus45h/inscription-data


output : 

{"code":-2003,"msg":"quota unavailable","data":null}
