### ISSUE TITLE
Wrong Taproot address example in documentation

### ISSUE THREAD

**Issue by wwwMalcolm** [unisat-wallet/dev-support#40]
As per the title above, it is related to this link https://docs.unisat.io/knowledge-base/bitcoin-basics/understanding-bitcoin-address-types#id-4.-taproot

The particular issue is located at Point 4. Taproot. The point written states that address format starts with "bc1p" but yet the given example is the exact same one found for Point 3. Native SegWit (bech32), which does not follow the point stating that addresses start with "bc1p"

**Comment by cloud6605** [comment]
Thanks for your feedback. We'll fix it as soon as possible.
