### ISSUE TITLE
403 Forbidden error

### ISSUE THREAD

**Issue by GiantDole** [unisat-wallet/dev-support#42]
Hey everyone,
I got a free API key from the developer.unisat.io page to test things out with runes. However, any API request to even basic endpoints fails with a 403 Forbidden error.
Could anyone help with this?

Thanks!

**Comment by huanniangstudio** [comment]
You can test your key on this page => https://open-api.unisat.io/swagger.html

<img width="443" alt="image" src="https://github.com/unisat-wallet/dev-support/assets/3053743/7a94b21a-5c78-492f-817b-71f1da6af3d8">

Please note the way to use the KEY. You need to set `Authorization: Bearer YOUR-API-KEY` in the request header.
