### ISSUE TITLE
Specialist plan api key got 403 response frequently

### ISSUE THREAD

**Issue by freddi8e** [unisat-wallet/dev-support#45]
Hi, I bought a Specialist plan apikeys with 10000 calls/day ， but  got 403 response frequently,  Could anyone help with this? Thanks.
<img width="437" alt="image" src="https://github.com/unisat-wallet/dev-support/assets/152241286/24c445f9-d6b4-49a4-a854-b63b5cb55721">

**Comment by abangZ** [comment]
We have fixed the issue, please try again.
