### ISSUE TITLE
“About Game Framework、Fractal Bitcoin、Uniworlds, some of my thoughts”

### ISSUE THREAD

**Issue by XYDHLJJ** [unisat-wallet/dev-support#5]
Fractal Bitcoin, a technology known as BSCP, is undoubtedly poised to ignite the entire Bitcoin ecosystem's underlying technological architecture this year. However, it seems that hardly anyone is paying attention to it on Twitter. 

I've read Unisat's complete blog post on the Fractal Bitcoin network on January 31st no less than five times. While I'm not particularly tech-savvy, I've been involved in inscriptions since entering the circle in May last year, and I've self-taught many things about the underlying logic and structure. I've listened to Lorenzo's discussions on inscriptions countless times, whether it's at the Space or the Ordinals Summit conference, or in interviews and podcasts.

Inscriptions, these small flowers born from the stone (Bitcoin), will undoubtedly grow into a fragrant garden where birds sing in the future. I firmly believe in this.

I initially wanted to develop a solution based on Ln + inscriptions to facilitate swaps on the Bitcoin layer one chain. I wonder if, after modifying the underlying source code of Ln, it can resolve the incompatibility issue between it and the (floating on the Bitcoin chain) inscriptions. I look forward to a resolution to this.

Regarding the longstanding dream of a full-chain game, or rather, this dream may have grown even larger, becoming a full-chain open framework for game development. Such a product/platform/tool needs to integrate inscriptions while requiring all code/split code to be uploaded to the chain (which is the essence of Bitcoin layer one inscriptions), whether it's for modularity or Generative inscriptions (which may include action/description/composite assets).

This necessitates the use of BSCP for underlying architectural support.

With Fractal Bitcoin, application launches, and the modular generation and transfer of assets on layer one, once this gateway is opened, what follows is an influx of countless web2/web3 traditional game giants entering the Bitcoin ecosystem, along with a plethora of traffic/capital and the launch of related product applications.

The future holds promise. Let me reintroduce myself once again. My name is Xiao Yi (Twitter XYDHLJJ). Last year, I conducted over 100 Ordinals/Brc20 educational Spaces for newcomers in the cryptocurrency circle.

**Comment by huanniangstudio** [comment]
Thank you for your support, we also have the same full-chain game dream.
