### ISSUE TITLE
Can't catch runeid from utxo

### ISSUE THREAD

**Issue by btcwhiz** [unisat-wallet/dev-support#63]
I can't get rune info from runes utxo.
https://open-api-testnet.unisat.io/v1/indexer/runes/utxo/1649dd0c5b50434de13b281a1a6213199a85838ed21dd068b56b2082d135bdaa/1/balance
 { code: 0, data: [] }

what happening here?

**Comment by cloud6605** [comment]
it works on my side.
![image](https://github.com/user-attachments/assets/2e7b2bee-3122-4b5b-b646-0d1ec5336374)

Please try again.
