### ISSUE TITLE
A first-level heading

### ISSUE THREAD

**Issue by mtengkusyahid** [unisat-wallet/dev-support#70]
![image_1725983775210682](https://github.com/user-attachments/assets/0628e315-5849-48a7-95ca-7e3af2318858)

**Comment by tengkusyahid** [comment]
./0000-template.md to ./text/0000-my-new-standard.md

**Comment by tengkusyahid** [comment]
Combot has warned NFTPRIEST (1/3)
Reason: Word **** is not allowed
